version: '3.8'

services:
  # Наш сервис базы данных
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: spike
      POSTGRES_PASSWORD: 1029384756
      POSTGRES_DB: rest_students
#    ports:
#      - "5432:5432"
    volumes:
      # Магия: база сама создаст таблицы из твоего скрипта при первом запуске
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  # Наше FastAPI приложение
  app:
    build: .
    image: rest-students-app
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  frontend:
    image: nginx:stable-alpine
    ports:
      - "80:80"  # Теперь сайт будет открываться просто по IP (без порта 8000)
    volumes:
      - ./frontend:/usr/share/nginx/html:ro # Пробрасываем папку с файлами внутрь Nginx
    depends_on:
      - app
volumes:
  postgres_data: